name: AMGNN
channels:
  - pytorch
  - pyg
  - defaults
dependencies:
  - xmltodict
  - cudatoolkit=11.3
  - numba=0.54.*
  - pandocfilters=1.5.*
  - pillow=8.4.*
  - pip
  - python=3.9.*
  - pytorch=1.11.*
  - pyg=2.1.0
  - pyyaml=6.*
  - packaging=21.3
  - pip:
    - protobuf==3.19.*
    - ninja
    - matplotlib==3.5.*
    - networkx==2.8.*
    - pandas==1.4.1
    - pathtools==0.1.2
    - pdoc3==0.10.0
    - plotly==5.10.0
    - polyscope==1.3.1
    - pytorch-lightning==1.8.2
    - pyvista==0.33.3
    - scikit-learn==1.1.*
    - scipy==1.9.*
    - tensorboard==2.11.0
    - tqdm==4.64.*
    - trimesh==3.10.2
    - vtk==9.1.0
    - wandb==0.13.4
    - class-resolver
    - -e git+https://github.com/lerouxl/Simufact_ARC_reader.git#egg=simufact_arc_reader

