optimizer: "adam"
learning_rate: 1e-06
neighbour_radius: 2e-03
neighbour_k: 26
input_channels: 18
hidden_channels: 128
number_hidden_layers: 1
out_channels: 4
aggregator: mean
distance_upper_bound: 1e-6
batch_size: 2
max_epochs: 1
