optimizer: "adam"
learning_rate: 1e-03
neighbour_k: 26
input_channels: 22
hidden_channels: 256
number_hidden_layers: 3
out_channels: 4
aggregator: mean
distance_upper_bound: 0.3 # Tolerance used for aligning old to new features (in mm)
batch_size: 15
max_epochs: 40
accumulate_grad_batches: 1
lambda_parameters: [1,1,1] # weight MSE loss, weight temperature gradient loss, weight displacement gradient loss
model_name: simple_conv

# Wandb parameters
offline: No # If Yes, wandb will not try to save the trainning online. If No, wandb will save the results online.
notes: "Run of AMGNN on one cube dataset CubeX1X150WX750mmsX8umX3um" # Note to add to the run
# Tags to give to this amgnn run
tags:
  - "train"
  - "one cube dataset"
  # - "simple mlp" Now the model name is automaticaly add to the tag