program: main.py
method: grid
metric:
  goal: minimize
  name: validation_loss
parameters:
  model_name:
    values: [ "simple_gnn", "simple_mlp", "double_head_simple_gnn", "double_head_simple_mlp" ]
  number_hidden_layers:
    values: [ 2, 4, 16]
  hidden_channels:
    values: [128, 256, 512]