program: main.py
method: grid
metric:
  goal: minimize
  name: "test loss"
parameters:
  model_name:
    values: [ "simple_gnn", "double_head_simple_gnn", "simple_mlp", "double_head_simple_mlp", "simple_conv", "double_head_simple_conv" ]
  lambda_parameters:
    values: [[1,0,0], [0.70,0.15,0.15]]