program: main.py
method: bayes
metric:
  goal: minimize
  name: validation_loss
parameters:
  learning_rate:
    min: 0.0001
    max: 0.1
  optimizer:
    values: [ "sgd", "adam" ]
  neighbour_k:
    vales: [6, 26 ]